export type fontFamilyType =
  | 'AntDesign'
  | 'Entypo'
  | 'EvilIcons'
  | 'Feather'
  | 'FontAwesome'
  | 'FontAwesome5'
  | 'Fontisto'
  | 'Foundation'
  | 'Ionicons'
  | 'MaterialCommunityIcons'
  | 'MaterialIcons'
  | 'Octicons'
  | 'SimpleLineIcons'
  | 'Zocial'
  | 'FontAwesome5Pro';

export type customFontFamilyType =
  | 'person'
  | 'lock'
  | 'name'
  | 'mobile'
  | 'password'
  | 'home'
  | 'my-bet'
  | 'withdrawal'
  | 'back'
  | 'bell'
  | 'game-rate'
  | 'feedback'
  | 'share'
  | 'how-to-play'
  | 'edit';
